/**
 * Kitchen OS — Noticing that a new version has arrived
 *
 * The service worker (generated by `vite.config.ts`) deliberately never
 * activates itself. It installs, then waits. This is the other half of that
 * arrangement: it registers the worker, notices when a new one is sitting in
 * the waiting state, and gives the shell something to put a banner behind.
 *
 * Why the waiting matters, restated because it is the whole point: browser
 * storage is the only copy of the kitchen. If a new worker took over silently
 * it could leave one window running Phase 8's code while another ran Phase 9's
 * — and if Phase 9 ships a schema v6, both would be open against the same
 * Dexie database mid-upgrade. Nothing here activates without a tap.
 *
 * Not unit tested, on purpose. There is no pure logic left in it once the
 * browser APIs are removed; it is covered end-to-end by `qa/smoke-phase8.cjs`,
 * which drives a real worker in a real browser.
 */
import { useCallback, useEffect, useRef, useState } from 'react'

export interface AppUpdate {
  /** A new version is downloaded and waiting for permission to take over. */
  readonly ready: boolean
  /** Activate the waiting version and reload. Only ever called from a tap. */
  readonly apply: () => void
}

/** Where the built worker lands, derived from Vite's base rather than typed twice. */
const SW_URL = `${import.meta.env.BASE_URL}sw.js`

export function useAppUpdate(): AppUpdate {
  const [ready, setReady] = useState(false)
  const waiting = useRef<ServiceWorker | null>(null)
  /**
   * Set the instant before we ask the worker to take over.
   *
   * `controllerchange` also fires the first time a worker ever claims this
   * page, which happens on a completely ordinary first visit. Reloading then
   * would be a mystifying flicker on launch, so the reload is gated on having
   * asked for it.
   */
  const requested = useRef(false)

  useEffect(() => {
    // No worker in development: Vite serves modules unbundled and there is no
    // sw.js to register. Registering one anyway would cache a dev server.
    if (!import.meta.env.PROD) return
    if (!('serviceWorker' in navigator)) return

    let abandoned = false
    let onVisible: (() => void) | null = null

    const offer = (worker: ServiceWorker | null) => {
      if (abandoned || worker === null) return
      waiting.current = worker
      setReady(true)
    }

    void navigator.serviceWorker
      .register(SW_URL, { scope: import.meta.env.BASE_URL })
      .then((registration) => {
        if (abandoned) return

        // Already waiting when the page loaded — the update arrived during a
        // previous sitting and nobody has tapped yet.
        offer(registration.waiting)

        registration.addEventListener('updatefound', () => {
          const installing = registration.installing
          if (installing === null) return
          installing.addEventListener('statechange', () => {
            // `installed` with a controller present means an UPDATE is waiting.
            // Without a controller it is the very first install, which is not
            // news worth showing anyone.
            if (installing.state === 'installed' && navigator.serviceWorker.controller !== null) {
              offer(installing)
            }
          })
        })

        /*
         * Ask whether there is a new version, every time the app comes back to
         * the foreground.
         *
         * The browser normally checks on navigation, and an app on a home
         * screen may go weeks without one — it is opened, used, and
         * backgrounded, never reloaded. Without this the banner would
         * effectively never appear on the one device this is built for, which
         * would make the whole update path decorative.
         *
         * Cheap: a conditional request for one small file, only when the app
         * is opened, and it fails silently offline.
         */
        onVisible = () => {
          if (document.visibilityState !== 'visible') return
          void registration.update().catch(() => {
            // Offline, or the server is unreachable. Nothing to say.
          })
        }
        document.addEventListener('visibilitychange', onVisible)
      })
      .catch(() => {
        // A worker that fails to register is not worth interrupting anyone
        // over: the app still works, it just will not open offline.
      })

    const onControllerChange = () => {
      if (!requested.current) return
      requested.current = false
      window.location.reload()
    }
    navigator.serviceWorker.addEventListener('controllerchange', onControllerChange)

    return () => {
      abandoned = true
      navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange)
      if (onVisible !== null) document.removeEventListener('visibilitychange', onVisible)
    }
  }, [])

  const apply = useCallback(() => {
    const worker = waiting.current
    if (worker === null) return
    requested.current = true
    // The banner is deliberately left up until the reload replaces the page.
    // Hiding it here would mean that if the handover somehow failed, the offer
    // would vanish and the update would never be mentioned again — a silent
    // dead end. Leaving it up costs a few hundred milliseconds of a banner
    // nobody sees, and stays retryable if something goes wrong.
    worker.postMessage('SKIP_WAITING')
  }, [])

  return { ready, apply }
}
