/**
 * Kitchen OS — Id generation
 *
 * Products and lots get a random id. Canonical ingredients do NOT come through
 * here: their ids are readable slugs generated by `generateIngredientId` in the
 * engine, because a recipe referencing "chicken-breast" is something a person
 * can read, and because collisions there have to be handled deliberately.
 *
 * Randomness lives here rather than in `src/engine/`, which stays pure.
 */

/** A fresh id, prefixed so it is obvious what it points at when debugging. */
export function newId(prefix: string): string {
  return `${prefix}_${crypto.randomUUID()}`
}
