/**
 * Phase 8 smoke test — installing, offline, and the update handshake.
 *
 * Unlike Phases 5 to 7 this one does NOT run against the dev server. Everything
 * it tests only exists in the built output: `sw.js` is generated by
 * `vite.config.ts` at build time, the manifest and icons are copied from
 * `public/`, and a service worker will not register over an unbundled dev
 * server anyway. So:
 *
 *     npm run build && node qa/smoke-phase8.cjs
 *
 * It serves `dist/` itself rather than leaning on `npm run preview`, because
 * the interesting half of this phase is what happens when a SECOND version
 * appears. The little server below can be told to start serving a byte-
 * different `sw.js`, which is exactly what a deploy looks like from the
 * browser's side — and that is the only honest way to watch the update banner
 * appear, wait, and then be tapped.
 *
 * The property being defended, restated: browser storage is the only copy of
 * the kitchen. A new worker must never activate on its own, because two
 * versions of the code open against one Dexie database is what migrations
 * handle worst. Steps 6 to 9 are all about that one sentence.
 */
function loadPlaywright() {
  for (const candidate of [
    'playwright',
    '/home/claude/.npm-global/lib/node_modules/playwright/index.js',
  ]) {
    try {
      return require(candidate)
    } catch {
      continue
    }
  }
  throw new Error('Playwright is not installed. `npm i -g playwright` and try again.')
}

const playwright = loadPlaywright()
const fs = require('node:fs')
const http = require('node:http')
const path = require('node:path')

const PORT = Number(process.env.PORT ?? 5175)
const BASE_PATH = '/kitchen-os/'
const BASE = process.env.BASE ?? `http://localhost:${String(PORT)}${BASE_PATH}`
const DIST = path.join(__dirname, '..', 'dist')
const SHOTS = process.env.SHOTS ?? '/tmp/kitchen-os-shots-8'

const TYPES = {
  '.css': 'text/css',
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.json': 'application/json',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.webmanifest': 'application/manifest+json',
}

/**
 * A static server over `dist/`, with one switch.
 *
 * While `deployed.second` is true it serves an altered `sw.js` — same
 * behaviour, different version string, therefore different bytes. The browser
 * compares the worker byte-for-byte, so that is all it takes to look like a new
 * deploy. Everything else is served straight off disk.
 */
const deployed = { second: false }

/** Every request for sw.js, so a failure can say whether the browser looked. */
const swRequests = []

function startServer() {
  const server = http.createServer((request, response) => {
    let rel = decodeURIComponent(new URL(request.url, BASE).pathname)
    if (!rel.startsWith(BASE_PATH)) {
      response.writeHead(404).end('outside the app')
      return
    }
    rel = rel.slice(BASE_PATH.length)
    if (rel === '') rel = 'index.html'

    const file = path.join(DIST, rel)
    if (!file.startsWith(DIST) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) {
      response.writeHead(404).end('not found')
      return
    }

    let body = fs.readFileSync(file)
    if (rel === 'sw.js') swRequests.push({ at: Date.now(), second: deployed.second })
    if (rel === 'sw.js' && deployed.second) {
      body = Buffer.from(
        body.toString('utf8').replace(/kitchen-os-([0-9a-f]{12})/g, 'kitchen-os-$1-v2'),
      )
    }

    response.writeHead(200, {
      'content-type': TYPES[path.extname(file)] ?? 'application/octet-stream',
      // No HTTP caching, so the browser's own cache never stands in for the
      // service worker's and the test measures what it thinks it measures.
      'cache-control': 'no-store',
    })
    response.end(body)
  })
  return new Promise((resolve) => {
    server.listen(PORT, () => {
      resolve(server)
    })
  })
}

async function main() {
  if (!fs.existsSync(path.join(DIST, 'sw.js'))) {
    throw new Error('dist/sw.js is missing. Run `npm run build` first.')
  }

  const server = await startServer()
  const sandboxChromium = '/opt/pw-browsers/chromium'
  const browser = await playwright.chromium.launch(
    fs.existsSync(sandboxChromium) ? { executablePath: sandboxChromium } : {},
  )
  fs.mkdirSync(SHOTS, { recursive: true })
  const context = await browser.newContext({ viewport: { width: 1180, height: 820 } })
  const page = await context.newPage()

  const problems = []
  page.on('console', (message) => {
    if (message.type() === 'error') problems.push(`console: ${message.text()}`)
  })
  page.on('pageerror', (error) => problems.push(`pageerror: ${error.message}`))

  const step = async (name, run) => {
    process.stdout.write(`• ${name}\n`)
    await run()
  }

  const expect = (actual, wanted, what) => {
    if (actual !== wanted) throw new Error(`${what}: got "${actual}", expected "${wanted}"`)
  }

  const sheet = page.locator('.sheet')

  /** Wait until a worker is controlling the page. */
  const waitForController = () =>
    page.waitForFunction(() => navigator.serviceWorker.controller !== null, null, {
      timeout: 15000,
    })

  const cacheNames = () => page.evaluate(() => caches.keys())

  const workerStates = () =>
    page.evaluate(async () => {
      const registration = await navigator.serviceWorker.getRegistration()
      return {
        active: registration?.active?.state ?? null,
        waiting: registration?.waiting?.state ?? null,
      }
    })

  /**
   * Poll `workerStates()` from here until it satisfies `wanted`.
   *
   * Deliberately NOT `page.waitForFunction`. Reading the registration needs an
   * async callback, and an async callback returns a Promise — which is truthy,
   * so the wait succeeds on its first poll no matter what the states actually
   * are. That cost an hour: the test passed the wait and then asserted against
   * a worker that had not finished installing.
   */
  const untilStates = async (wanted, what, timeoutMs = 20000, nudge) => {
    const deadline = Date.now() + timeoutMs
    let last = null
    let nudgedAt = 0
    while (Date.now() < deadline) {
      // Re-poke whatever is supposed to make this happen, about once a second,
      // rather than firing once and hoping.
      if (nudge !== undefined && Date.now() - nudgedAt > 1000) {
        nudgedAt = Date.now()
        await nudge()
      }
      last = await workerStates()
      if (wanted(last)) return last
      await page.waitForTimeout(200)
    }
    throw new Error(`${what}: timed out with states ${JSON.stringify(last)}`)
  }

  await step('the page loads from the repository subpath', async () => {
    await page.goto(BASE, { waitUntil: 'networkidle' })
    // A base-path mistake shows up here and nowhere else: the document loads
    // and the bundle 404s, so the root stays empty and nothing throws.
    await page.waitForSelector('.brand', { timeout: 15000 })
    expect((await page.textContent('.brand')).trim(), 'Kitchen OS', 'the app rendered')
  })

  await step('the manifest and the icons are reachable, and say the right things', async () => {
    const href = await page.getAttribute('link[rel="manifest"]', 'href')
    expect(href, `${BASE_PATH}manifest.webmanifest`, 'manifest href')

    const manifest = await page.evaluate(async (url) => {
      const response = await fetch(url)
      return { ok: response.ok, body: await response.json() }
    }, href)
    if (!manifest.ok) throw new Error('the manifest did not load')

    expect(manifest.body.name, 'Kitchen OS', 'manifest name')
    expect(manifest.body.display, 'standalone', 'display mode')
    expect(manifest.body.orientation, 'landscape', 'orientation')
    // Relative on purpose: resolved against the manifest's own URL, so the
    // subpath is written down in exactly one place.
    expect(manifest.body.start_url, './#/today', 'start_url')

    const icons = [
      await page.getAttribute('link[rel="apple-touch-icon"]', 'href'),
      ...manifest.body.icons.map((icon) => new URL(icon.src, BASE + 'manifest.webmanifest').pathname),
    ]
    for (const icon of icons) {
      const ok = await page.evaluate(async (url) => (await fetch(url)).ok, icon)
      if (!ok) throw new Error(`icon ${icon} did not load`)
    }
  })

  await step('the worker registers and takes control', async () => {
    await waitForController()
    const states = await workerStates()
    expect(states.active, 'activated', 'worker state')
    expect(states.waiting, null, 'nothing waiting after a first install')

    const names = await cacheNames()
    if (names.length !== 1) throw new Error(`expected one cache, found ${JSON.stringify(names)}`)
  })

  await step('the first install does not reload the page underneath you', async () => {
    // `clients.claim()` fires `controllerchange` on a perfectly ordinary first
    // visit. If the reload were not gated on the User having asked, the app
    // would flicker on launch for no reason anybody could explain.
    const marker = await page.evaluate(() => {
      window.__phase8 = 'still here'
      return window.__phase8
    })
    expect(marker, 'still here', 'marker set')
    await page.waitForTimeout(1500)
    expect(await page.evaluate(() => window.__phase8 ?? null), 'still here', 'page was not reloaded')
  })

  /*
   * The second deploy goes live HERE, several steps before anything looks for
   * it.
   *
   * That is how a deploy actually happens: it lands at some moment, and the app
   * finds it whenever it next looks. Publishing it and demanding the browser
   * notice within the same second was the source of a one-in-three flake —
   * Chromium rate-limits update checks, and no amount of asking harder moves
   * it. Giving the check somewhere natural to happen removes the race instead
   * of racing it.
   */
  deployed.second = true

  await step('put something in the kitchen, so the update has something to lose', async () => {
    await page.waitForSelector('.kit-list')
    await page.click('.actions button.primary')
    await page.waitForSelector('.kit-list', { state: 'detached', timeout: 10000 })

    await page.click('text=+ Add to the kitchen')
    await page.fill('.search', 'olive oil')
    await page.waitForSelector('.pick-name:has-text("Olive oil")')
    await page.click('.pick:has-text("Olive oil")')

    await sheet.locator('input[placeholder="Kroger Boneless Chicken Breast"]').fill('Phase 8 Oil')
    await sheet.locator('select').first().selectOption('per100g')
    await sheet.locator('label:has-text("Package size") input').fill('500')
    await sheet.locator('.macro-grid input').nth(0).fill('884')
    await page.click('text=Save product')

    await page.waitForSelector('text=Add to the kitchen')
    await page.click('.actions button.primary')
    await page.waitForSelector('.sheet', { state: 'detached', timeout: 10000 })
  })

  await step('a new version installs but does NOT take over', async () => {
    const before = await page.evaluate(
      () => navigator.serviceWorker.controller?.scriptURL ?? null,
    )

    /*
     * Getting the browser to go and look, which is harder than it sounds.
     *
     * Two triggers, alternating, and the mixture is deliberate.
     *
     * The `visibilitychange` event is the one the APP listens for, and firing
     * it exercises the real wiring rather than reaching around it. On a
     * home-screen app it is also the only trigger that will ever fire on its
     * own: the app is opened, used and backgrounded, and can go weeks without a
     * navigation.
     *
     * But `registration.update()` — what that handler calls — is not reliable.
     * Measured here over many runs: Chromium honours it sometimes and ignores
     * it completely other times, with no request leaving the browser at all for
     * thirty seconds of asking once a second. It is not a short throttle that
     * can be waited out, and asking harder does not help.
     *
     * A document load does work, every time, and it is the browser's own update
     * trigger. So every third attempt reopens the app. That is a real thing a
     * person does, and it is what makes this suite deterministic — five runs in
     * five with it, two failures in five without.
     *
     * The caveat this leaves in the product is written down in DECISIONS.md: an
     * installed app that is never relaunched may be slower to notice a new
     * version than the foreground check implies. Harmless for a personal recipe
     * app, and iOS relaunches a suspended PWA often enough in practice.
     *
     * (A dispatched event is not a real backgrounding — Playwright cannot give
     * us one. It does prove the listener is wired to the update check.)
     */
    let attempt = 0
    const foreground = async () => {
      attempt++
      await page.evaluate(() => {
        document.dispatchEvent(new Event('visibilitychange'))
      })
      // Every third attempt, reopen the app instead. A fresh document load is
      // the browser's own update trigger and does not depend on it honouring a
      // scripted check.
      if (attempt % 3 === 0) {
        await page.reload({ waitUntil: 'load' })
        await page.waitForSelector('.brand', { timeout: 15000 })
      }
    }

    const states = await untilStates(
      (s) => s.waiting !== null,
      `the new worker never reached the waiting state (sw.js requests seen: ${String(swRequests.length)})`,
      30000,
      foreground,
    )
    expect(states.waiting, 'installed', 'the new worker is waiting, not activated')
    expect(states.active, 'activated', 'the old worker is still the active one')

    // The controlling worker has not changed. This is the whole safety
    // property: nothing swapped, so nothing could be half-migrated.
    const after = await page.evaluate(() => navigator.serviceWorker.controller?.scriptURL ?? null)
    expect(after, before, 'the controller did not change on its own')

    const names = await cacheNames()
    if (names.length !== 2) {
      throw new Error(`expected the old and new caches to coexist, found ${JSON.stringify(names)}`)
    }
  })

  await step('the banner says so, and offers exactly one thing', async () => {
    await page.waitForSelector('.banner-update', { timeout: 15000 })
    const text = await page.textContent('.banner-update')
    if (!text.includes('A new version of Kitchen OS is ready.')) {
      throw new Error(`update banner reads "${text}"`)
    }
    const buttons = page.locator('.banner-update button')
    expect(await buttons.count(), 1, 'buttons on the update banner')
    expect((await buttons.textContent()).trim(), 'Reload', 'the button')

    // 44pt minimum, per CLAUDE.md. Easy to lose when a control is added to a
    // strip that was laid out for something else.
    const box = await buttons.boundingBox()
    if (box.height < 44) throw new Error(`the Reload button is ${String(box.height)}px tall`)

    await page.screenshot({ path: `${SHOTS}/update-banner.png` })
  })

  await step('tapping Reload activates the new version and reloads once', async () => {
    await Promise.all([
      page.waitForNavigation({ waitUntil: 'load', timeout: 20000 }),
      page.click('.banner-update button'),
    ])
    await page.waitForSelector('.brand', { timeout: 15000 })
    await waitForController()

    const states = await untilStates(
      (s) => s.waiting === null && s.active === 'activated',
      'the new worker never took over after the tap',
    )
    expect(states.waiting, null, 'nothing left waiting')
    expect(states.active, 'activated', 'the new worker is active')

    // The old cache is gone, so the next launch cannot fall back to old code.
    const names = await cacheNames()
    if (names.length !== 1 || !names[0].endsWith('-v2')) {
      throw new Error(`expected only the new cache, found ${JSON.stringify(names)}`)
    }

    await page.waitForSelector('.banner-update', { state: 'detached', timeout: 10000 })
  })

  await step('the kitchen survived the update', async () => {
    await page.goto(`${BASE}#/inventory`, { waitUntil: 'networkidle' })
    await page.waitForSelector('text=Olive oil', { timeout: 15000 })
  })

  /*
   * Offline comes AFTER the update dance, not before it, and the ordering is
   * load-bearing rather than tidy.
   *
   * An update check that fails because the network is gone makes Chromium back
   * off before it will try again — sensibly, but for longer than a test wants
   * to wait, and unpredictably. Going offline immediately before asking for an
   * update therefore made this suite fail about one run in three, with the
   * worker never reaching the waiting state.
   *
   * That backoff is correct behaviour and harmless in real use: a missed check
   * means the next foreground finds the update. It only breaks a test that
   * demands one within seconds. Testing offline AFTER the swap is also the
   * more interesting order — it proves the NEW worker serves offline too.
   */
  await step('it opens with no network at all', async () => {
    await context.setOffline(true)
    await page.goto(`${BASE}#/recipes`, { waitUntil: 'load' })
    await page.waitForSelector('.brand', { timeout: 15000 })
    await page.goto(`${BASE}#/inventory`, { waitUntil: 'load' })
    await page.waitForSelector('text=Olive oil', { timeout: 15000 })
    await page.screenshot({ path: `${SHOTS}/offline.png` })
    await context.setOffline(false)
  })

  await step('the worker never reaches off-origin', async () => {
    const offOrigin = []
    page.on('request', (request) => {
      if (!request.url().startsWith(`http://localhost:${String(PORT)}`)) {
        offOrigin.push(request.url())
      }
    })
    await page.goto(`${BASE}#/recipes`, { waitUntil: 'networkidle' })
    await page.waitForTimeout(1000)
    if (offOrigin.length > 0) {
      throw new Error(`the app asked for something off-origin:\n  ${offOrigin.join('\n  ')}`)
    }
  })

  if (problems.length > 0) {
    throw new Error(`browser reported problems:\n  ${problems.join('\n  ')}`)
  }

  await context.close()
  await browser.close()
  server.close()
  process.stdout.write(`\nAll steps passed. Screenshots in ${SHOTS}\n`)
}

main().catch((error) => {
  process.stderr.write(`\nSMOKE FAILED: ${error.message}\n`)
  process.exit(1)
})
